import gleam/dict
import gleam/list
import gleam/option.{None}
import gleam/string
import gleeunit
import gleeunit/should
import simplifile
import sqlode/codegen
import sqlode/codegen/common
import sqlode/model
import sqlode/naming
import sqlode/query_analyzer
import sqlode/query_parser
import sqlode/runtime
import sqlode/schema_parser

pub fn main() {
  gleeunit.main()
}

pub fn render_queries_module_test() {
  let naming_ctx = naming.new()
  let block = test_block()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered = codegen.render_queries_module(naming_ctx, block, analyzed)

  string.contains(
    rendered,
    "pub fn get_author() -> runtime.RawQuery(params.GetAuthorParams) {",
  )
  |> should.be_true()
  string.contains(rendered, "import sqlode/runtime")
  |> should.be_true()
  string.contains(rendered, "import db/params")
  |> should.be_true()
  string.contains(rendered, "command: runtime.QueryOne")
  |> should.be_true()
  string.contains(rendered, "encode: params.get_author_values,")
  |> should.be_true()
  string.contains(rendered, "slice_info: fn(_) { [] },")
  |> should.be_true()
  string.contains(rendered, "pub fn all() -> List(runtime.QueryInfo) {")
  |> should.be_true()
  list.length(analyzed) |> should.equal(2)
  // Parameterless query should use Nil type and inline encode
  string.contains(rendered, "pub fn list_authors() -> runtime.RawQuery(Nil) {")
  |> should.be_true()
  string.contains(rendered, "encode: fn(_) { [] },")
  |> should.be_true()
}

pub fn render_params_module_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered =
    codegen.render_params_module(
      naming_ctx,
      analyzed,
      model.StringMapping,
      "db",
    )

  string.contains(rendered, "pub type GetAuthorParams {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorParams(id: Int)")
  |> should.be_true()
  string.contains(rendered, "runtime.int(params.id)")
  |> should.be_true()
  // Parameterless queries should NOT generate Params type
  string.contains(rendered, "pub type ListAuthorsParams {")
  |> should.be_false()
  string.contains(rendered, "list_authors_values")
  |> should.be_false()
}

pub fn render_models_module_test() {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  string.contains(rendered, "// Code generated by sqlode. DO NOT EDIT.")
  |> should.be_true()
  // Table type should be emitted
  string.contains(rendered, "pub type Author {")
  |> should.be_true()
  // Query row types (partial match — only id, name from 3-column table)
  string.contains(rendered, "pub type GetAuthorRow {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorRow(id: Int, name: String)")
  |> should.be_true()
  string.contains(rendered, "pub type ListAuthorsRow {")
  |> should.be_true()
  string.contains(rendered, "ListAuthorsRow(id: Int, name: String)")
  |> should.be_true()
}

pub fn render_models_module_with_nullable_test() {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let analyzed = analyzed_star_queries()
  let table_matches = dict.from_list([#("get_all_authors", "Author")])
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      table_matches,
      model.StringMapping,
      False,
    )

  string.contains(rendered, "import gleam/option.{type Option}")
  |> should.be_true()
  string.contains(rendered, "bio: Option(String)")
  |> should.be_true()
  // SELECT * matches table exactly, should emit alias
  string.contains(rendered, "pub type GetAllAuthorsRow =")
  |> should.be_true()
}

pub fn render_models_module_no_exec_rows_test() {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let analyzed = analyzed_queries("test/fixtures/create_query.sql")
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  // No Row types for exec queries, but table type should still be present
  string.contains(rendered, "pub type Author {")
  |> should.be_true()
}

pub fn render_pog_adapter_test() {
  let naming_ctx = naming.new()
  let block = test_block_native()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  string.contains(rendered, "import pog") |> should.be_true()
  string.contains(rendered, "import db/models") |> should.be_true()
  string.contains(rendered, "import db/params") |> should.be_true()
  string.contains(rendered, "import db/queries") |> should.be_true()
  string.contains(rendered, "pub fn get_author(db: pog.Connection")
  |> should.be_true()
  string.contains(rendered, "pog.query(q.sql)") |> should.be_true()
  string.contains(rendered, "pog.parameter(pog.int(p.id))")
  |> should.be_true()
  string.contains(rendered, "decode.success(models.GetAuthorRow(")
  |> should.be_true()
  string.contains(rendered, "pub fn list_authors(db: pog.Connection)")
  |> should.be_true()
}

pub fn render_sqlight_adapter_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.SQLite,
      schema: ["test/fixtures/schema.sql"],
      queries: ["test/fixtures/query.sql"],
      gleam: model.GleamOutput(
        out: "test_output/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )

  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])
  let assert Ok(content) = simplifile.read("test/fixtures/query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/query.sql",
      model.SQLite,
      naming_ctx,
      content,
    )
  let assert Ok(analyzed) =
    query_analyzer.analyze_queries(model.SQLite, catalog, naming_ctx, queries)
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  string.contains(rendered, "import sqlight") |> should.be_true()
  string.contains(rendered, "pub fn get_author(db: sqlight.Connection")
  |> should.be_true()
  string.contains(rendered, "sqlight.query(") |> should.be_true()
  string.contains(rendered, "decode.success(models.GetAuthorRow(")
  |> should.be_true()
}

pub fn render_params_module_slice_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_slice_queries(model.PostgreSQL)
  let rendered =
    codegen.render_params_module(
      naming_ctx,
      analyzed,
      model.StringMapping,
      "db",
    )

  // The type should use List(...) for slice params
  string.contains(rendered, "ids: List(")
  |> should.be_true()
  // Should use list.flatten for values function
  string.contains(rendered, "list.flatten(")
  |> should.be_true()
  string.contains(rendered, "list.map(params.ids, runtime.")
  |> should.be_true()
  // Should import gleam/list
  string.contains(rendered, "import gleam/list")
  |> should.be_true()
}

pub fn render_pog_adapter_slice_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.PostgreSQL,
      schema: ["test/fixtures/schema.sql"],
      queries: ["test/fixtures/macro_edge_cases.sql"],
      gleam: model.GleamOutput(
        out: "test_output/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let analyzed = analyzed_slice_queries(model.PostgreSQL)
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Should import runtime for slice expansion
  string.contains(rendered, "import sqlode/runtime")
  |> should.be_true()
  // Should call expand_slice_placeholders
  string.contains(rendered, "runtime.expand_slice_placeholders(")
  |> should.be_true()
  // Should use list.fold for slice param binding
  string.contains(rendered, "list.fold(p.ids")
  |> should.be_true()
  // Should use let query = style
  string.contains(rendered, "let query = pog.query(sql)")
  |> should.be_true()
}

pub fn render_sqlight_adapter_slice_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.SQLite,
      schema: ["test/fixtures/schema.sql"],
      queries: ["test/fixtures/macro_edge_cases.sql"],
      gleam: model.GleamOutput(
        out: "test_output/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let analyzed = analyzed_slice_queries(model.SQLite)
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Should call expand_slice_placeholders with "?" prefix
  string.contains(rendered, "runtime.expand_slice_placeholders(")
  |> should.be_true()
  // Should use list.flatten for sqlight params
  string.contains(rendered, "list.flatten(")
  |> should.be_true()
  string.contains(rendered, "list.map(p.ids, sqlight.")
  |> should.be_true()
}

pub fn expand_slice_placeholders_single_test() {
  let sql = "SELECT id, name FROM authors WHERE id IN ($1)"
  let result = runtime.expand_slice_placeholders(sql, [#(1, 3)], 1, "$")
  result
  |> should.equal("SELECT id, name FROM authors WHERE id IN ($1, $2, $3)")
}

pub fn expand_slice_placeholders_with_renumbering_test() {
  let sql = "SELECT * FROM users WHERE name = $1 AND id IN ($2) AND status = $3"
  let result = runtime.expand_slice_placeholders(sql, [#(2, 3)], 3, "$")
  result
  |> should.equal(
    "SELECT * FROM users WHERE name = $1 AND id IN ($2, $3, $4) AND status = $5",
  )
}

pub fn expand_slice_placeholders_sqlite_test() {
  let sql = "SELECT id, name FROM authors WHERE id IN (?1)"
  let result = runtime.expand_slice_placeholders(sql, [#(1, 2)], 1, "?")
  result
  |> should.equal("SELECT id, name FROM authors WHERE id IN (?1, ?2)")
}

pub fn expand_slice_placeholders_no_slices_test() {
  let sql = "SELECT * FROM users WHERE id = $1"
  let result = runtime.expand_slice_placeholders(sql, [], 1, "$")
  result |> should.equal("SELECT * FROM users WHERE id = $1")
}

pub fn expand_slice_placeholders_empty_slice_test() {
  let sql = "SELECT * FROM users WHERE id IN ($1)"
  let result = runtime.expand_slice_placeholders(sql, [#(1, 0)], 1, "$")
  result |> should.equal("SELECT * FROM users WHERE id IN (NULL)")
}

pub fn expand_slice_placeholders_empty_slice_with_other_params_test() {
  let sql = "SELECT * FROM users WHERE name = $1 AND id IN ($2) AND status = $3"
  let result = runtime.expand_slice_placeholders(sql, [#(2, 0)], 3, "$")
  result
  |> should.equal(
    "SELECT * FROM users WHERE name = $1 AND id IN (NULL) AND status = $2",
  )
}

pub fn expand_slice_placeholders_empty_slice_sqlite_test() {
  let sql = "SELECT * FROM users WHERE id IN (?1)"
  let result = runtime.expand_slice_placeholders(sql, [#(1, 0)], 1, "?")
  result |> should.equal("SELECT * FROM users WHERE id IN (NULL)")
}

// --- Table type and alias tests ---

pub fn render_models_table_type_alias_for_exact_match_test() {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let analyzed = analyzed_star_queries()
  let table_matches = dict.from_list([#("get_all_authors", "Author")])
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      table_matches,
      model.StringMapping,
      False,
    )

  // Table type should be emitted
  string.contains(rendered, "pub type Author {")
  |> should.be_true()
  string.contains(
    rendered,
    "Author(id: Int, name: String, bio: Option(String))",
  )
  |> should.be_true()
  // Exact match should produce alias, not duplicate record
  string.contains(rendered, "pub type GetAllAuthorsRow =")
  |> should.be_true()
  string.contains(rendered, "GetAllAuthorsRow =\n  Author")
  |> should.be_true()
}

pub fn render_models_partial_match_generates_row_type_test() {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  // Partial match (only id, name from 3-column table) should NOT produce alias
  string.contains(rendered, "pub type GetAuthorRow {")
  |> should.be_true()
  string.contains(rendered, "pub type GetAuthorRow =")
  |> should.be_false()
}

pub fn render_adapter_uses_table_constructor_for_match_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.PostgreSQL,
      schema: ["test/fixtures/schema.sql"],
      queries: ["test/fixtures/query.sql"],
      gleam: model.GleamOutput(
        out: "test_output/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let analyzed = analyzed_star_queries()
  let table_matches = dict.from_list([#("get_all_authors", "Author")])
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, table_matches)

  // When matched, decoder should use table constructor
  string.contains(rendered, "decode.success(models.Author(")
  |> should.be_true()
  // Return type should still use the Row alias
  string.contains(rendered, "models.GetAllAuthorsRow")
  |> should.be_true()
}

// --- Test helpers ---

fn analyzed_slice_queries(engine: model.Engine) -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])
  let sql =
    "-- name: GetByIds :many\nSELECT id, name FROM authors WHERE id IN (sqlode.slice(ids));"
  let assert Ok(queries) =
    query_parser.parse_file("slice.sql", engine, naming_ctx, sql)
  let assert Ok(result) =
    query_analyzer.analyze_queries(engine, catalog, naming_ctx, queries)
  result
}

fn test_block() -> model.SqlBlock {
  model.SqlBlock(
    name: None,
    engine: model.PostgreSQL,
    schema: ["test/fixtures/schema.sql"],
    queries: ["test/fixtures/query.sql"],
    gleam: model.GleamOutput(
      out: "src/db",
      runtime: model.Raw,
      type_mapping: model.StringMapping,
      emit_sql_as_comment: False,
      emit_exact_table_names: False,
    ),
    overrides: model.empty_overrides(),
  )
}

fn test_block_native() -> model.SqlBlock {
  model.SqlBlock(
    name: None,
    engine: model.PostgreSQL,
    schema: ["test/fixtures/schema.sql"],
    queries: ["test/fixtures/query.sql"],
    gleam: model.GleamOutput(
      out: "src/db",
      runtime: model.Native,
      type_mapping: model.StringMapping,
      emit_sql_as_comment: False,
      emit_exact_table_names: False,
    ),
    overrides: model.empty_overrides(),
  )
}

fn test_catalog() -> model.Catalog {
  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])
  catalog
}

fn analyzed_queries(path: String) -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let catalog = test_catalog()
  let assert Ok(content) = simplifile.read(path)
  let assert Ok(queries) =
    query_parser.parse_file(path, model.PostgreSQL, naming_ctx, content)

  let assert Ok(result) =
    query_analyzer.analyze_queries(
      model.PostgreSQL,
      catalog,
      naming_ctx,
      queries,
    )
  result
}

// --- Enum type tests ---

pub fn render_enum_from_string_returns_result_test() {
  let naming_ctx = naming.new()
  let catalog = enum_test_catalog()
  let analyzed = enum_analyzed_queries()
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  // from_string should return Result
  string.contains(
    rendered,
    "pub fn status_from_string(value: String) -> Result(Status, String) {",
  )
  |> should.be_true()

  // Valid values should return Ok
  string.contains(rendered, "\"active\" -> Ok(Active)")
  |> should.be_true()
  string.contains(rendered, "\"inactive\" -> Ok(Inactive)")
  |> should.be_true()
  string.contains(rendered, "\"banned\" -> Ok(Banned)")
  |> should.be_true()

  // Unknown values should return Error
  string.contains(rendered, "_ -> Error(\"Unknown status value: \" <> value)")
  |> should.be_true()
}

pub fn render_enum_decoder_uses_decode_then_test() {
  let naming_ctx = naming.new()
  let analyzed = enum_analyzed_queries()

  let block =
    model.SqlBlock(
      name: None,
      engine: model.PostgreSQL,
      schema: ["test/fixtures/enum_schema.sql"],
      queries: ["test/fixtures/enum_query.sql"],
      gleam: model.GleamOutput(
        out: "src/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Should use decode.then, not decode.map for enums
  string.contains(rendered, "decode.then(decode.string")
  |> should.be_true()
  string.contains(rendered, "status_from_string")
  |> should.be_true()
  string.contains(rendered, "decode.success(v)")
  |> should.be_true()
  string.contains(rendered, "decode.failure(s")
  |> should.be_true()

  // Should NOT use decode.map for enum decoding
  string.contains(
    rendered,
    "decode.map(decode.string, models.status_from_string",
  )
  |> should.be_false()
}

fn enum_test_catalog() -> model.Catalog {
  let assert Ok(schema_content) =
    simplifile.read("test/fixtures/enum_schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([
      #("test/fixtures/enum_schema.sql", schema_content),
    ])
  catalog
}

fn enum_analyzed_queries() -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let catalog = enum_test_catalog()
  let assert Ok(content) = simplifile.read("test/fixtures/enum_query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/enum_query.sql",
      model.PostgreSQL,
      naming_ctx,
      content,
    )
  let assert Ok(result) =
    query_analyzer.analyze_queries(
      model.PostgreSQL,
      catalog,
      naming_ctx,
      queries,
    )
  result
}

pub fn render_pog_adapter_enum_slice_converts_to_string_test() {
  let naming_ctx = naming.new()
  let analyzed = enum_analyzed_queries()

  let block =
    model.SqlBlock(
      name: None,
      engine: model.PostgreSQL,
      schema: ["test/fixtures/enum_schema.sql"],
      queries: ["test/fixtures/enum_query.sql"],
      gleam: model.GleamOutput(
        out: "src/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Slice enum params should call to_string before pog.text
  string.contains(rendered, "models.status_to_string(v)")
  |> should.be_true()
  string.contains(rendered, "pog.text(models.status_to_string(v))")
  |> should.be_true()
}

pub fn render_sqlight_adapter_enum_slice_converts_to_string_test() {
  let naming_ctx = naming.new()
  let catalog = enum_test_catalog()
  let assert Ok(content) = simplifile.read("test/fixtures/enum_query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/enum_query.sql",
      model.SQLite,
      naming_ctx,
      content,
    )
  let assert Ok(analyzed) =
    query_analyzer.analyze_queries(model.SQLite, catalog, naming_ctx, queries)

  let block =
    model.SqlBlock(
      name: None,
      engine: model.SQLite,
      schema: ["test/fixtures/enum_schema.sql"],
      queries: ["test/fixtures/enum_query.sql"],
      gleam: model.GleamOutput(
        out: "src/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Slice enum params should call to_string before sqlight.text
  string.contains(rendered, "models.status_to_string(v)")
  |> should.be_true()
  string.contains(
    rendered,
    "fn(v) { sqlight.text(models.status_to_string(v)) }",
  )
  |> should.be_true()
}

// --- README snapshot tests ---
// These tests verify that the README code examples match actual generated output.
// If a test here fails, it means the README examples are stale and need updating.

pub fn readme_params_snapshot_test() {
  let naming_ctx = naming.new()
  let analyzed = readme_analyzed_queries()
  let rendered =
    codegen.render_params_module(
      naming_ctx,
      analyzed,
      model.StringMapping,
      "db",
    )

  // README: pub type GetAuthorParams { GetAuthorParams(id: Int) }
  string.contains(rendered, "pub type GetAuthorParams {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorParams(id: Int)")
  |> should.be_true()

  // README: pub fn get_author_values(params: GetAuthorParams) -> List(Value) {
  //           [runtime.int(params.id)]
  string.contains(rendered, "runtime.int(params.id)")
  |> should.be_true()

  // README: pub type CreateAuthorParams { CreateAuthorParams(... bio: Option(String)) }
  string.contains(rendered, "pub type CreateAuthorParams {")
  |> should.be_true()
  string.contains(rendered, "bio: Option(String)")
  |> should.be_true()

  // README sqlode.slice: pub type GetAuthorsByIdsParams { GetAuthorsByIdsParams(ids: List(Int)) }
  string.contains(rendered, "pub type GetAuthorsByIdsParams {")
  |> should.be_true()
  string.contains(rendered, "ids: List(Int)")
  |> should.be_true()
}

pub fn readme_models_snapshot_test() {
  let naming_ctx = naming.new()
  let catalog = readme_test_catalog()
  let analyzed = readme_analyzed_queries()
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  // README: pub type Author { Author(id: Int, name: String, bio: Option(String)) }
  string.contains(rendered, "pub type Author {")
  |> should.be_true()
  string.contains(
    rendered,
    "Author(id: Int, name: String, bio: Option(String))",
  )
  |> should.be_true()

  // README: partial match produces separate row type
  string.contains(rendered, "pub type GetAuthorRow {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorRow(id: Int, name: String)")
  |> should.be_true()

  // README: pub type ListAuthorsRow { ListAuthorsRow(id: Int, name: String) }
  string.contains(rendered, "pub type ListAuthorsRow {")
  |> should.be_true()

  // README sqlode.embed: pub type GetBookWithAuthorRow {
  //   GetBookWithAuthorRow(authors: Author, title: String) }
  string.contains(rendered, "pub type GetBookWithAuthorRow {")
  |> should.be_true()
  string.contains(
    rendered,
    "GetBookWithAuthorRow(authors: Author, title: String)",
  )
  |> should.be_true()
}

pub fn readme_queries_snapshot_test() {
  let naming_ctx = naming.new()
  let block = readme_test_block()
  let analyzed = readme_analyzed_queries()
  let rendered = codegen.render_queries_module(naming_ctx, block, analyzed)

  // README: pub fn get_author() -> runtime.RawQuery(params.GetAuthorParams) { ... }
  string.contains(
    rendered,
    "pub fn get_author() -> runtime.RawQuery(params.GetAuthorParams) {",
  )
  |> should.be_true()

  // Parameterless query should use Nil type parameter
  string.contains(rendered, "pub fn list_authors() -> runtime.RawQuery(Nil) {")
  |> should.be_true()

  // README: pub fn create_author() -> runtime.RawQuery(params.CreateAuthorParams)
  string.contains(
    rendered,
    "pub fn create_author() -> runtime.RawQuery(params.CreateAuthorParams) {",
  )
  |> should.be_true()

  // QueryInfo is now in runtime, not generated inline
  string.contains(rendered, "pub type QueryInfo {")
  |> should.be_false()

  // all() uses runtime.QueryInfo
  string.contains(rendered, "pub fn all() -> List(runtime.QueryInfo) {")
  |> should.be_true()
}

fn readme_test_catalog() -> model.Catalog {
  let assert Ok(schema_content) =
    simplifile.read("test/fixtures/readme_schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([
      #("test/fixtures/readme_schema.sql", schema_content),
    ])
  catalog
}

fn readme_test_block() -> model.SqlBlock {
  model.SqlBlock(
    name: None,
    engine: model.PostgreSQL,
    schema: ["test/fixtures/readme_schema.sql"],
    queries: ["test/fixtures/readme_query.sql"],
    gleam: model.GleamOutput(
      out: "src/db",
      runtime: model.Raw,
      type_mapping: model.StringMapping,
      emit_sql_as_comment: False,
      emit_exact_table_names: False,
    ),
    overrides: model.empty_overrides(),
  )
}

fn readme_analyzed_queries() -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let catalog = readme_test_catalog()
  let assert Ok(content) = simplifile.read("test/fixtures/readme_query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/readme_query.sql",
      model.PostgreSQL,
      naming_ctx,
      content,
    )
  let assert Ok(result) =
    query_analyzer.analyze_queries(
      model.PostgreSQL,
      catalog,
      naming_ctx,
      queries,
    )
  result
}

// --- Array type tests ---

pub fn array_schema_parsing_test() {
  let catalog = array_test_catalog()
  let assert [table] = catalog.tables
  let cols = table.columns
  // tags should be ArrayType(StringType)
  let assert [_, _, tags_col, scores_col] = cols
  tags_col.scalar_type |> should.equal(model.ArrayType(model.StringType))
  scores_col.scalar_type |> should.equal(model.ArrayType(model.IntType))
}

pub fn render_models_with_array_columns_test() {
  let naming_ctx = naming.new()
  let catalog = array_test_catalog()
  let analyzed = array_analyzed_queries()
  let rendered =
    codegen.render_models_module(
      naming_ctx,
      catalog,
      analyzed,
      dict.new(),
      model.StringMapping,
      False,
    )

  // Table type should have List fields for array columns (nullable since no NOT NULL)
  string.contains(rendered, "tags: Option(List(String))")
  |> should.be_true()
  string.contains(rendered, "scores: Option(List(Int))")
  |> should.be_true()
}

pub fn render_params_with_array_columns_test() {
  let naming_ctx = naming.new()
  let analyzed = array_analyzed_queries()
  let rendered =
    codegen.render_params_module(
      naming_ctx,
      analyzed,
      model.StringMapping,
      "db",
    )

  // Params for CreateArticle should have array fields (nullable since no NOT NULL)
  string.contains(rendered, "tags: Option(List(String))")
  |> should.be_true()
  string.contains(rendered, "scores: Option(List(Int))")
  |> should.be_true()
}

pub fn render_params_array_encoding_raw_runtime_test() {
  let naming_ctx = naming.new()
  let analyzed = array_analyzed_queries()
  let rendered =
    codegen.render_params_module(
      naming_ctx,
      analyzed,
      model.StringMapping,
      "db",
    )

  // Raw-mode array params should encode using runtime.array + list.map
  string.contains(rendered, "runtime.array(list.map(")
  |> should.be_true()

  // Nullable array params should use runtime.nullable wrapping runtime.array
  string.contains(rendered, "runtime.nullable(")
  |> should.be_true()

  // Should import gleam/list for array mapping
  string.contains(rendered, "import gleam/list")
  |> should.be_true()
}

pub fn render_pog_adapter_with_array_columns_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.PostgreSQL,
      schema: ["test/fixtures/array_schema.sql"],
      queries: ["test/fixtures/array_query.sql"],
      gleam: model.GleamOutput(
        out: "src/db",
        runtime: model.Native,
        type_mapping: model.StringMapping,
        emit_sql_as_comment: False,
        emit_exact_table_names: False,
      ),
      overrides: model.empty_overrides(),
    )
  let analyzed = array_analyzed_queries()
  let rendered =
    codegen.render_adapter_module(naming_ctx, block, analyzed, dict.new())

  // Decoder should use decode.list for array result columns
  string.contains(rendered, "decode.list(decode.string)")
  |> should.be_true()
  string.contains(rendered, "decode.list(decode.int)")
  |> should.be_true()

  // Parameter encoding should use pog.array for array params
  string.contains(rendered, "pog.array(pog.text)")
  |> should.be_true()
  string.contains(rendered, "pog.array(pog.int)")
  |> should.be_true()
}

fn array_test_catalog() -> model.Catalog {
  let assert Ok(schema_content) =
    simplifile.read("test/fixtures/array_schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([
      #("test/fixtures/array_schema.sql", schema_content),
    ])
  catalog
}

fn array_analyzed_queries() -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let catalog = array_test_catalog()
  let assert Ok(content) = simplifile.read("test/fixtures/array_query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/array_query.sql",
      model.PostgreSQL,
      naming_ctx,
      content,
    )
  let assert Ok(result) =
    query_analyzer.analyze_queries(
      model.PostgreSQL,
      catalog,
      naming_ctx,
      queries,
    )
  result
}

pub fn out_to_module_path_strips_src_prefix_test() {
  common.out_to_module_path("src/db") |> should.equal("db")
  common.out_to_module_path("src/generated/db") |> should.equal("generated/db")
  common.out_to_module_path("/absolute/path/src/db") |> should.equal("db")
  common.out_to_module_path("/abs/src/generated/db")
  |> should.equal("generated/db")
  common.out_to_module_path("test_output/db") |> should.equal("test_output/db")
  // Multiple /src/ segments — take the part after the last /src/
  common.out_to_module_path("/home/src/project/src/db") |> should.equal("db")
  common.out_to_module_path("/home/src/project/src/generated/db")
  |> should.equal("generated/db")
}

fn analyzed_star_queries() -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let catalog = test_catalog()

  let sql = "-- name: GetAllAuthors :many\nSELECT * FROM authors;"
  let assert Ok(queries) =
    query_parser.parse_file("star.sql", model.PostgreSQL, naming_ctx, sql)

  let assert Ok(result) =
    query_analyzer.analyze_queries(
      model.PostgreSQL,
      catalog,
      naming_ctx,
      queries,
    )
  result
}

// --- escape_string tests ---

pub fn escape_string_backslash_test() {
  common.escape_string("a\\b") |> should.equal("a\\\\b")
}

pub fn escape_string_double_quote_test() {
  common.escape_string("say \"hello\"") |> should.equal("say \\\"hello\\\"")
}

pub fn escape_string_newline_and_tab_test() {
  common.escape_string("line1\nline2\ttab")
  |> should.equal("line1\\nline2\\ttab")
}

pub fn escape_string_carriage_return_test() {
  common.escape_string("a\rb") |> should.equal("a\\rb")
}

pub fn escape_string_no_special_chars_test() {
  common.escape_string("hello world") |> should.equal("hello world")
}
