import gleam/list
import gleam/option.{None}
import gleam/string
import gleeunit
import gleeunit/should
import simplifile
import sqlode/codegen
import sqlode/model
import sqlode/naming
import sqlode/query_analyzer
import sqlode/query_parser
import sqlode/schema_parser

pub fn main() {
  gleeunit.main()
}

pub fn render_queries_module_test() {
  let block = test_block()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered = codegen.render_queries_module(block, analyzed)

  string.contains(rendered, "pub fn get_author() -> Query {")
  |> should.be_true()
  string.contains(rendered, "import sqlode/runtime")
  |> should.be_true()
  string.contains(rendered, "command: runtime.QueryOne")
  |> should.be_true()
  string.contains(rendered, "pub fn all() -> List(Query) {")
  |> should.be_true()
  list.length(analyzed) |> should.equal(2)
}

pub fn render_params_module_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered = codegen.render_params_module(naming_ctx, analyzed)

  string.contains(rendered, "pub type GetAuthorParams {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorParams(id: Int)")
  |> should.be_true()
  string.contains(rendered, "runtime.int(params.id)")
  |> should.be_true()
  string.contains(rendered, "pub type ListAuthorsParams {")
  |> should.be_true()
  string.contains(
    rendered,
    "pub fn list_authors_values(_params: ListAuthorsParams) -> List(Value) {",
  )
  |> should.be_true()
}

pub fn render_models_module_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered = codegen.render_models_module(naming_ctx, analyzed)

  string.contains(rendered, "// Code generated by sqlode. DO NOT EDIT.")
  |> should.be_true()
  string.contains(rendered, "pub type GetAuthorRow {")
  |> should.be_true()
  string.contains(rendered, "GetAuthorRow(id: Int, name: String)")
  |> should.be_true()
  string.contains(rendered, "pub type ListAuthorsRow {")
  |> should.be_true()
  string.contains(rendered, "ListAuthorsRow(id: Int, name: String)")
  |> should.be_true()
}

pub fn render_models_module_with_nullable_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_star_queries()
  let rendered = codegen.render_models_module(naming_ctx, analyzed)

  string.contains(rendered, "import gleam/option.{type Option}")
  |> should.be_true()
  string.contains(rendered, "bio: Option(String)")
  |> should.be_true()
}

pub fn render_models_module_no_exec_rows_test() {
  let naming_ctx = naming.new()
  let analyzed = analyzed_queries("test/fixtures/create_query.sql")
  let rendered = codegen.render_models_module(naming_ctx, analyzed)

  string.contains(rendered, "Row") |> should.be_false()
}

pub fn render_pog_adapter_test() {
  let naming_ctx = naming.new()
  let block = test_block_native()
  let analyzed = analyzed_queries("test/fixtures/query.sql")
  let rendered = codegen.render_adapter_module(naming_ctx, block, analyzed)

  string.contains(rendered, "import pog") |> should.be_true()
  string.contains(rendered, "import db/models") |> should.be_true()
  string.contains(rendered, "import db/params") |> should.be_true()
  string.contains(rendered, "import db/queries") |> should.be_true()
  string.contains(rendered, "pub fn get_author(db: pog.Connection")
  |> should.be_true()
  string.contains(rendered, "pog.query(q.sql)") |> should.be_true()
  string.contains(rendered, "pog.parameter(pog.int(p.id))")
  |> should.be_true()
  string.contains(rendered, "decode.success(models.GetAuthorRow(")
  |> should.be_true()
  string.contains(rendered, "pub fn list_authors(db: pog.Connection)")
  |> should.be_true()
}

pub fn render_sqlight_adapter_test() {
  let naming_ctx = naming.new()
  let block =
    model.SqlBlock(
      name: None,
      engine: model.SQLite,
      schema: ["test/fixtures/schema.sql"],
      queries: ["test/fixtures/query.sql"],
      gleam: model.GleamOutput(
        package: "db",
        out: "test_output/db",
        runtime: model.Native,
      ),
      overrides: model.empty_overrides(),
    )

  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])
  let assert Ok(content) = simplifile.read("test/fixtures/query.sql")
  let assert Ok(queries) =
    query_parser.parse_file(
      "test/fixtures/query.sql",
      model.SQLite,
      naming_ctx,
      content,
    )
  let analyzed =
    query_analyzer.analyze_queries(model.SQLite, catalog, naming_ctx, queries)
  let rendered = codegen.render_adapter_module(naming_ctx, block, analyzed)

  string.contains(rendered, "import sqlight") |> should.be_true()
  string.contains(rendered, "pub fn get_author(db: sqlight.Connection")
  |> should.be_true()
  string.contains(rendered, "sqlight.query(") |> should.be_true()
  string.contains(rendered, "decode.success(models.GetAuthorRow(")
  |> should.be_true()
}

fn test_block() -> model.SqlBlock {
  model.SqlBlock(
    name: None,
    engine: model.PostgreSQL,
    schema: ["test/fixtures/schema.sql"],
    queries: ["test/fixtures/query.sql"],
    gleam: model.GleamOutput(
      package: "db",
      out: "test_output/db",
      runtime: model.Raw,
    ),
    overrides: model.empty_overrides(),
  )
}

fn test_block_native() -> model.SqlBlock {
  model.SqlBlock(
    name: None,
    engine: model.PostgreSQL,
    schema: ["test/fixtures/schema.sql"],
    queries: ["test/fixtures/query.sql"],
    gleam: model.GleamOutput(
      package: "db",
      out: "test_output/db",
      runtime: model.Native,
    ),
    overrides: model.empty_overrides(),
  )
}

fn analyzed_queries(path: String) -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])
  let assert Ok(content) = simplifile.read(path)
  let assert Ok(queries) =
    query_parser.parse_file(path, model.PostgreSQL, naming_ctx, content)

  query_analyzer.analyze_queries(model.PostgreSQL, catalog, naming_ctx, queries)
}

fn analyzed_star_queries() -> List(model.AnalyzedQuery) {
  let naming_ctx = naming.new()
  let assert Ok(schema_content) = simplifile.read("test/fixtures/schema.sql")
  let assert Ok(catalog) =
    schema_parser.parse_files([#("test/fixtures/schema.sql", schema_content)])

  let sql = "-- name: GetAllAuthors :many\nSELECT * FROM authors;"
  let assert Ok(queries) =
    query_parser.parse_file("star.sql", model.PostgreSQL, naming_ctx, sql)

  query_analyzer.analyze_queries(model.PostgreSQL, catalog, naming_ctx, queries)
}
