name = "sqlode"
version = "0.4.0"
target = "erlang"
description = "Generate type-safe Gleam code from SQL schemas and queries"
licences = ["MIT"]
repository = { type = "github", user = "nao1215", repo = "sqlode" }
links = [
  { title = "Homepage", href = "https://github.com/nao1215/sqlode" },
  { title = "Documentation", href = "https://hexdocs.pm/sqlode" },
  { title = "Changelog", href = "https://github.com/nao1215/sqlode/blob/main/CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
yay = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.2 and < 2.0.0"
